[package]
name = "ncexe"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "^1"
clap = { version = "^4.4.8", features = ["derive"]}
dirs = "^5.0"
hex = "^0"
hex-literal = "^0"
memmap2 = "0"
pancurses = "0.17"
serde = { version = "^1.0", features = ["derive"] }
serde_yaml = "^0.9"
