[package]
name = "ncmacho"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap2 = "0"
clap = { version = "4.4.8", features = ["derive"]}
derive = "1.0.0"
features = "0.10.0"
